language: bash
sudo: required

services:
  - docker

branches:
  only:
    - source

before_install:
  - echo -e "machine github.com\n  login $GH_TOKEN" >> ~/.netrc

script:
  - ./scripts/run.sh build-prod
  - test $TRAVIS_PULL_REQUEST == "false" && sudo chown -R $USER ./dist && ./scripts/publish.sh

env:
  global:
    - secure: "Y4QTlZEy0G5T8LNi8w+Iehg3K5msR7pnzJxhzu3KQWw7XgDqp2G25wRSD64HIK4kCKIknuveZJqI7ifKnezHQgthVl0ksfv5mfmMqotgrVWuyYkrJLhbGJmEN3sjuRecyZzMDlFwk941w27VWUsiN282mI7A8oHUlrVYLpiQVfVS4UIJFSBA0LX4JeiqOlLWYkXJS+p/tnQ1AgRQz3aDgIekuT2D692iSn0qb2pcPjcB8nz6b0BHxHDQkBpmV5+zK8t/cWXc729+3b9ncH0s6IhKIu2MUCV8n0VW2yj0461GfaHcVZ2nxrhdE6rdzJkr4Sxs/F95IeQYeR8sWj5xwRn9R4bCG/jri+SuZBgkWImHS4GUOTM1TTOcRITX4LegwZ8u2f27tG/ZheyZf+WXIdiqgd0OeDzYl1QAnUK+YJCN6VarYttAMSAXilKp78f934puX+bti+UpECyuFMBcVRu1rT+QxErzx+WNhaufE6CXfVFuEDMv6VfG4PzBWb9GZI+q0Ql+GZCbN8T8fK7yMVzQ1B6nIQdQ8xb/kmIuavtCB7MpqEB++Uou0cd/m47YAVcMfAmqAlGdWMHUXeOcXuuZXkIhNdEYI6RxhQODJGPngZ8OSPb6j9BfAZKLy17WvqUfjfkhGTPvW3seJ5hhJMQ3x8v8OZD/d0UH1DaEdP0="

