language: bash
sudo: required

services:
  - docker

branches:
  only:
    - source

before_install:
  - echo -e "machine github.com\n  login $GH_TOKEN" >> ~/.netrc

script:
  - ./scripts/run.sh build-prod
  - test $TRAVIS_PULL_REQUEST == "false" && sudo chown -R $USER ./dist && ./scripts/publish.sh

env:
  global:
    - secure: "RZcpu1iCyDhjoHghJ8Y35h3jZHGtLuKvMHfoef5P0zcj+2En/teLmYpcEMtJWMTCiYLfeHZtSaHPN/LFyIQCn5BeT+7Ks4JnbvKE5uuCib8a6bkSrJetPFzSe2DQLRHJTdQFg3dtCDzhG41jYvc+Mo4PU266uMgD7u5YnsWmoGD8hGeBiD+w7dPtn1PIQsOiupf3jdfyBJloWi2TWSPGzlQFj2B2I19pRS7botlHoZLbBiuFgxNIVAYYcBeC7e+RqGWe0BAVWBslND8q9HD9kEd+JtvUVZBLLcjo2hx0lSeiLBGFJOuW9OF7T50KDxBcmgBjS7fvFbpvEmgxRmRgFv0JGSuO6LIPDAQxUNCFngYqUaqkONiFA87SsIo0tToUYd5D3bDLqTgw3jJ1g4BBQcSUsKDDPqT8zjFHlHidNyk4Ps3DoXAP+CS4TAyMR6vLvKoTQ7iht/z3Y+HTdOO8H/+QgIv81F73OgKl52dzpBLoHephh14Qa0haF9IFwc8ByvDqey6ZowH0BZngP7kZ+uat6mx4w9I1MUHMf5Je7gFi9Ivp6t0tCh/JIZGoWzY+bk4yoJD9rB0LJiGzrzgcMNi/QKuClChjlNSkT7qtbLUP8zYEDOfLlWpd7EnEdMtafBSAIxfYCAOJ3MMAxdL8NfiAtrdhV6v+JaPfBH3pGKI="

notifications:
  slack:
    secure: EK9UOrPdqPREbNC6BclujxLJ4p4oGokmTo/xI/DafJED76B9oj2m7kOSy4JDNgUP1H5uS0WJdIrvvyqdRXiB3jo9cYFslprBBLU5y7yf00Q5z7QYOEkEgoxg0ScSDtywOaK+6FoTC3sBvijyUL6NIzBhmLMzhfUHxTJ0rbcqtHDMPRUPar449ocmIXQublkMC3jiOWL+W8p39yGen4p6zk3wEIQYPp6Pq2053de6gRCwcO++EsUvFM4UQ/+tCyZmKRTJJFw8frKBJd7JFFK4k1R8FiMIJ9qqr/357eVbI2tyYVHb/x/5Sh53igIbhIVYl/Qn8dR2s8ds81p7oRjGqSxesRdwnLd5c3++48yrjxqrFl7qAVHDMRzOo58JzNjP/UES53xJnP1N0i9yvwkfQLy0+6KPOVK+tQ5uBszvoK7i4I6bXeUArQxGIyOmUAArSif65/7Y9o5339VRd+B2pVHXRDsz89+QuZEkWHIvHo+jVVdhF7np8DoYwKm4fn3lcMQ/wrbRHGIKRnWOPpxeoJgBE9y7GvfSm5e0835dTESttiJkPE9YsaESQrPVzzEdFdUthUENgKcT182199+k2KJRewKVzDnpdG4IsivV4t6RiGHxN06HNZQEV9YkuaLPzFOGNzj5yQZDSbDMW2nSYeMxybF/sKMuskRzdcgQu1E=

